@startuml
'https://plantuml.com/sequence-diagram

skinparam maxMessageSize 150

title AddCommand (for Tasks)

actor User
participant ":Apollo" as Apollo
participant ":Parser" as Parser
participant ":AddCommand" as add
participant ":Event" as Event
participant ":TaskList" as TaskList
participant ":Calendar" as Calendar
participant ":Ui" as Ui
participant ":Storage" as Storage

User -> Apollo : "event concert /from 2023-06-06T20:00 /to 2023-06-06T22:00"
activate Apollo
Apollo -> Parser : getCommand()
activate Parser
Parser -> add** : AddCommand()
add++
add -> add ++ : setUpLogger()
add--
return
return

Apollo -> add : execute()
activate add
add -> add++ : addTask()
add -> Event** : new Event()
Event++
return
add -> add++ : isClashingEvent()
TaskList --> add
add--
alt Event clashes with Task
add -> Ui : printClashingEventMessage()
end
add -> add++ : warnEventModuleClash()
Calendar --> add
alt Event clashes with Lesson
add -> Ui : printClashingEventModuleMessage()
end
add--
add -> TaskList++ : add()
add--
add <-- TaskList--

add -> Ui : printAddMessage()
add -> Storage ++ : updateTask()
return
return
destroy add
Apollo--
@enduml