@startuml
'https://plantuml.com/sequence-diagram
skinparam maxMessageSize 150
title DateCommand (Find tasks by date)

actor User
participant ":Apollo" as Apollo
participant ":Parser" as Parser
participant ":DateCommand" as Date
participant ":TaskList" as TaskList
participant ":Task" as Task
participant ":Ui" as Ui
participant ":LocalDate" as LocalDate

User -> Apollo : "date 2023-03-30"
activate Apollo
Apollo -> Parser : getCommand()
activate Parser
Parser ->  Date** : DateCommand()
activate Date
Date -> Date: setUpLogger()
activate Date
deactivate Date

Date -> LocalDate: parse(2023-03-30)
activate LocalDate
LocalDate --> Date: date
deactivate LocalDate
destroy LocalDate
Date --> Parser : DateCommand()
deactivate Date

Parser --> Apollo
deactivate Parser
destroy Parser

Apollo -> Date : execute()
activate Date
Date --> TaskList : getTasksOnDate()
activate TaskList
TaskList -> TaskList++ : tasksOnDate = new TaskList()
loop for each Task in TaskList
    TaskList -> Task: isOnDate()
    activate Task
    Task --> TaskList :
    deactivate Task
    destroy Task
    alt task occurs during date
    TaskList -> TaskList : add()
    end
end
TaskList --> Date : tasksOnDate

deactivate TaskList
destroy TaskList


Date -> Ui : printDateList(tasksOnDate,date)
activate Ui
Ui --> Date
deactivate Ui
destroy Ui
Date --> Apollo
destroy Date
deactivate Apollo



@enduml