@startuml
'https://plantuml.com/sequence-diagram

skinparam maxMessageSize 150
title ModifyCommand (Unmark Tasks)

actor User
participant ":Apollo" as Apollo
participant ":Parser" as Parser
participant ":ModifyCommand" as modify

participant ":TaskList" as TaskList
participant ":Ui" as Ui
participant ":Storage" as Storage

User -> Apollo : "unmark 1"
activate Apollo
Apollo -> Parser : getCommand()
activate Parser
Parser -> modify** : ModifyCommand()
activate modify
modify --> Parser: new ModifyCommand
deactivate modify



Parser -> modify : execute()

activate modify
modify -> modify++ : unmarkTask()
TaskList --> modify
modify --
alt Task marked as complete previously
modify -> TaskList++: get()
TaskList -> TaskList ++ :setDone()
return
modify <-- TaskList--
destroy TaskList
modify -> Ui : ui.printMarkNotDone()
activate Ui
Ui --> modify
deactivate Ui

modify -> Storage: updateTask()
activate Storage
Storage --> modify
destroy Storage






else Task marked as incomplete previously

modify -> Ui : ui.printTaskHasBeenMarkedPreviously()
activate Ui
Ui --> modify
deactivate Ui
destroy Ui
end
modify --> Parser
destroy modify
Parser --> Apollo
destroy Parser

deactivate Apollo

@enduml