@startuml
'https://plantuml.com/sequence-diagram

skinparam maxMessageSize 150

title Parser

actor User

participant ":Apollo" as Apollo
participant ":Parser" as Parser
participant ":ShowModuleCommand" as Command
participant ":Module" as Module
participant ":Ui" as Ui

User -> Apollo : "showmod cs2113"
activate Apollo
Apollo -> Parser : getCommand()

activate Parser
Parser -> Parser : parseCommand()
activate Parser
Parser --> Parser : parseCommand()
deactivate Parser

opt "showmod"
Parser -> Parser : isEmptyParam()
activate Parser
Parser -> Ui :printErrorMessage()
activate Ui
deactivate Parser

Ui --> Parser
deactivate Ui
destroy Ui


else "showmod cs2113"


Parser -> Command** : ShowModuleCommand()
activate Command
Command -> Command : setUpLogger()
activate Command
deactivate Command

Command -> Module** : Module()
activate Module
Module --> Command : module
deactivate Module
destroy Module

Command --> Parser : ShowModuleCommand()
deactivate Command
destroy Command


end

Parser --> Apollo
deactivate Parser
destroy Parser

deactivate Apollo

@enduml