@startuml
'https://plantuml.com/sequence-diagram

skinparam maxMessageSize 150

title ShowModuleCommand

actor User

participant ":Apollo" as Apollo
participant ":Parser" as Parser
participant ":ShowModuleCommand" as ShowMod
participant ":ModuleList" as ModuleList
participant ":Module" as Module
participant ":Ui" as Ui

User -> Apollo : "showmod cs2113 -tut"

activate Apollo
Apollo -> Parser : getCommand()
activate Parser

Parser -> ShowMod** : ShowModuleCommand()
activate ShowMod

ShowMod -> ShowMod : setUpLogger()
activate ShowMod
deactivate ShowMod

ShowMod -> Module** : Module()
activate Module
Module --> ShowMod : module
deactivate Module
destroy Module

ShowMod --> Parser : ShowModuleCommand()
deactivate ShowMod

Parser --> Apollo
deactivate Parser
destroy Parser

Apollo -> ShowMod : execute()
activate ShowMod

ShowMod -> ModuleList : findModule(module)
activate ModuleList
ModuleList --> ShowMod
deactivate ModuleList
destroy ModuleList


alt args.length == 2
ShowMod -> ShowMod : handleMultiCommand()
activate ShowMod
ShowMod -> Ui : printModuleTimetable()
activate Ui
Ui --> ShowMod
deactivate Ui

deactivate ShowMod

else
ShowMod -> ShowMod : handleSingleCommand()
activate ShowMod
ShowMod -> Ui : printShowModuleMessage()

activate Ui
Ui --> ShowMod
deactivate Ui

deactivate ShowMod

end

destroy Ui

ShowMod --> Apollo

deactivate ShowMod
destroy ShowMod

deactivate Apollo




@enduml