@startuml
'https://plantuml.com/sequence-diagram

skinparam maxMessageSize 100

title WeekCommand

actor User
participant ":Apollo" as Apollo
participant ":Parser" as Parser
participant ":WeekCommand" as week
participant ":Ui" as Ui
participant ":SemesterUtils" as SemUtils
participant ":DayTypeUtil" as DayTypeUtil
participant ":Calendar" as Calendar
participant ":TaskList" as TaskList

User -> Apollo : "week"
activate Apollo
Apollo -> Parser : getCommand()
activate Parser
Parser -> week** : WeekCommand()
week++
return
return
destroy Parser

Apollo -> week : execute()
activate week

week -> Ui : printWeek()
activate Ui
Ui -> SemUtils : getWeekNumber()

Ui -> Ui++ : printEachDayInWeek()

loop 7 times
    Ui -> DayTypeUtil : determineDay()

    Ui -> Calendar : getModulesForDay()
    activate Calendar
    Calendar --> Ui : lessonsOnDay
    destroy Calendar
    opt There are lessons on that day
    Ui -> Ui : printLessonsOnDay()
    end

    Ui -> TaskList : getTasksOnDate()
    activate TaskList
    TaskList --> Ui : tasksOnDay
    destroy TaskList
    opt There are tasks on that day
    Ui -> Ui : printTasksOnDay()
    end
end
week <-- Ui--
destroy Ui
week --> Apollo
destroy week
Apollo--

@enduml