@startuml
'https://plantuml.com/sequence-diagram

title WeekCommand

actor User
participant ":Apollo" as Apollo
participant ":Parser" as Parser
participant ":WeekCommand" as week
participant ":Ui" as Ui
participant ":DayTypeUtil" as DayTypeUtil
participant ":Calendar" as Calendar
participant ":TaskList" as TaskList

User -> Apollo : "week"
activate Apollo
Apollo -> Parser : getCommand()
activate Parser
Parser -> week** : WeekCommand()
week++
return
return

Apollo -> week : execute()
activate week


week -> Ui : printWeek()
activate Ui

loop 7 times
    Ui -> DayTypeUtil : determineDay()
    activate DayTypeUtil
    return
    destroy DayTypeUtil

    Ui -> Calendar : get()
    activate Calendar
    Calendar --> Ui : lessonsOnDay
    destroy Calendar
    alt lessonsOnDay.size() > 0
    Ui -> Ui : printLessonsOnDay()
    activate Ui
    deactivate Ui
    end

    Ui -> TaskList : getTasksOnDate()
    activate TaskList
    TaskList --> Ui : tasksOnDay
    destroy TaskList
    alt tasksOnDay.size() > 0
    Ui -> Ui : printTasksOnDay()
    activate Ui
    deactivate Ui
    end
end
destroy Ui
week --> Apollo
destroy week
Apollo--

@enduml