@startuml
class seedu.meal360.Parser {
~ Ui ui
+ String combineWords(String[],int,int)
+ HashMap<String,Integer> parseIngredientName(String[])
+ Recipe parseAddRecipe(String[],RecipeList)
+ Recipe parseEditRecipe(String[],RecipeList)
+ String parseDeleteRecipe(String[],RecipeList)
+ String parseTagRecipe(String[],RecipeList)
+ String parseAddRecipeTag(String,RecipeList)
+ String parseRemoveRecipeTag(String,RecipeList)
+ RecipeList parseListRecipe(String[],RecipeList)
+ Recipe parseViewRecipe(String[],RecipeList)
+ Recipe parseViewRecipe(String,RecipeList)
+ Recipe parseRandomRecipe(RecipeList)
+ WeeklyPlan parseWeeklyPlan(String[],RecipeList)
- WeeklyPlan parseEditSingleWeeklyPlan(String[],RecipeList)
- WeeklyPlan parseEditMultiWeeklyPlan(String[],RecipeList)
- StringBuilder getRecipeNames(String[],ArrayList<String>,StringBuilder,int,int)
+ LocalDate parseDate(String)
+ void parseAddUserIngredients(String[],IngredientList)
+ void parseDeleteUserIngredients(String[],IngredientList)
}
@enduml