@startuml
'https://plantuml.com/sequence-diagram
title RemoveCommand Sequence Diagram

skinparam style strictuml
participant ":RemoveParser"
group sd [remove item in RemoveCommand]
    ":RemoveParser" -> ":RemoveCommand": run()
participant "Ui" <<class>>
    activate ":RemoveCommand"
        ":RemoveCommand" -> ":RemoveCommand": removeByUpcCode() or removeByIndex()
        activate ":RemoveCommand" #cyan
        ref over ":RemoveCommand"
            remove item
        end ref
        ":RemoveCommand" -> Ui: printSuccessRemove()
        activate Ui
        return successful remove message
        deactivate
    end
return
destroy ":RemoveCommand"
destroy ":RemoveParser"

@enduml