@startuml
'https://plantuml.com/sequence-diagram

actor User
User -> RemoveParser: run()
activate RemoveParser
alt rawInput contains 'f/item'
    RemoveParser -> RemoveParser: parseRemoveByUpc(commands, inventory)
    activate RemoveParser #cyan
    RemoveParser -> RemoveCommand: run()
    activate RemoveCommand
        ref over RemoveCommand
         check confirmation and execute accordingly
        end ref
    return
    return
else rawInput contains 'f'index'
    RemoveParser -> RemoveParser: parseRemoveByIndex(commands, inventory)
    activate RemoveParser #cyan
    RemoveParser -> RemoveCommand: run()
    activate RemoveCommand
        ref over RemoveCommand
         check confirmation and execute accordingly
        end ref
    return
    return
else rawInput is null/empty
    RemoveParser -> RemoveParser: null
end
destroy RemoveCommand
return
destroy RemoveParser
@enduml