@startuml
'https://plantuml.com/sequence-diagram

actor User

skinparam style strictuml
User -> ":RemoveParser": run()
activate ":RemoveParser"
alt rawInput contains 'f/upc' or 'f/index

    ":RemoveParser" -> ":RemoveParser": parseRemoveByUpc() or parseRemoveByIndex()
    activate ":RemoveParser" #cyan
    ref over ":RemoveParser"
    remove item in RemoveCommand
    end ref
    return null
else rawInput is null/empty
    ":RemoveParser" -> ":RemoveParser": null
end

return
destroy ":RemoveParser"
@enduml