
@startuml
title AddParser Sequence Diagram

participant ":ParserHandler" as ParserHandler
participant ":AddParser" as AddParser
ParserHandler -> AddParser: run()

activate AddParser
participant "<<class>>\nUi"
opt rawInput == null
AddParser -> MissingParametersException:throw missingAddItemParameters
activate MissingParametersException
MissingParametersException --> ParserHandler:
deactivate MissingParametersException
destroy MissingParametersException
end

opt !matcher.matches
AddParser -> "<<class>>\nUi":printInvalidAddCommand()
activate "<<class>>\nUi"
"<<class>>\nUi" --> ParserHandler:
deactivate "<<class>>\nUi"
end
participant ":AddCommand" as AddCommand
participant ":Command" as Command
AddParser -> AddCommand**: AddCommand(inventory, newItem)
activate AddCommand
AddCommand -->AddParser:
deactivate AddCommand

AddParser -> AddCommand: run()
activate AddCommand

AddCommand -> Command**:Command(inventory)
activate Command
Command -->AddCommand:
deactivate Command
destroy Command
AddCommand -->AddParser:
deactivate AddCommand
destroy AddCommand

AddParser --> ParserHandler:
destroy AddParser
@enduml