@startuml
'https://plantuml.com/sequence-diagram

[-> ":RemoveCommand": new RemoveCommand("egg", 2)

activate ":RemoveCommand"

":RemoveCommand" -> ":IngredientList": getIngredients()
activate ":IngredientList"
":RemoveCommand" <-- ":IngredientList": ArrayList<Ingredient>: ingredients
deactivate ":IngredientList"

":RemoveCommand" -> ":IngredientList": findIndex("egg")
activate ":IngredientList"
":RemoveCommand" <-- ":IngredientList": -1
deactivate ":IngredientList"


":RemoveCommand" -> ":IngredientList": get(index)
activate ":IngredientList"
":IngredientList" -> ":Ingredient": getQuantity()
activate ":Ingredient"
":IngredientList" <-- ":Ingredient": 5
deactivate ":Ingredient"
":RemoveCommand" <-- ":IngredientList":5
deactivate ":IngredientList"


":RemoveCommand" -> ":IngredientList": get(index)
activate ":IngredientList"
":IngredientList" -> ":Ingredient": setQuantity(3)
activate ":Ingredient"
":IngredientList" <-- ":Ingredient":
deactivate ":Ingredient"
":RemoveCommand" <-- ":IngredientList":
deactivate ":IngredientList"

[<-- ":RemoveCommand": Done
destroy ":RemoveCommand"
deactivate ":RemoveCommand"
@enduml