package seedu.dukeofbooks.common;

public class DefaultBooks {
    public static final String DEFAULT_BOOK_DATABASE = 
        "ISBN: 978-0131872486\n"
        + "Title: Thinking in Java\n"
        + "Author: Bruce Eckel\n"
        + "Topic: Computer Programming\n"
        + "NEXTBOOK\n"
        + "ISBN: 978-0275967765\n"
        + "Title: Cpp Programming Language\n"
        + "Author: Bjarne Stroustrup\n"
        + "Topic: Computer Programming\n"
        + "NEXTBOOK\n"
        + "ISBN: 978-1133608424\n"
        + "Title: Data Structures and Algorithms in Cpp\n"
        + "Author: Adam Drozdek\n"
        + "Topic: Data Structures and Algorithms\n"
        + "NEXTBOOK\n"
        + "ISBN: 978-1119800361\n"
        + "Title: Operating System Concepts\n"
        + "Author: Abraham Silberschatz\n"
        + "Topic: Operating Systems\n"
        + "NEXTBOOK\n"
        + "ISBN: 978-1492051299\n"
        + "Title: Head First Python A Learner Guide to the Fundamentals of Python Programming\n"
        + "Author: Paul Barry\n"
        + "Topic: Computer Programming\n"
        + "NEXTBOOK\n"
        + "ISBN: 978-0201835953\n"
        + "Title: The Mythical Man Month Essays on Software Engineering\n"
        + "Author: Frederick P Brooks\n"
        + "Topic: Software Engineering\n"
        + "NEXTBOOK\n"
        + "ISBN: 978-0357433836\n"
        + "Title: Guide to Operating Systems\n"
        + "Author: Greg Tomsho\n"
        + "Topic: Operating Systems\n"
        + "NEXTBOOK\n"
        + "ISBN: 978-0135957059\n"
        + "Title: The Pragmatic Programmer Your journey to mastery\n"
        + "Author: David Thomas\n"
        + "Topic: Software Engineering\n"
        + "NEXTBOOK\n"
        + "ISBN: 978-0262033848\n"
        + "Title: Introduction to Algorithms\n"
        + "Author: Thomas H Cormen\n"
        + "Topic: Data Structures and Algorithms\n"
        + "NEXTBOOK\n"
        + "ISBN: 978-8131773383\n"
        + "Title: Clean Code A Handbook of Agile Software Craftsmanship\n"
        + "Author: Robert C Martin\n"
        + "Topic: Software Engineering\n"
        + "NEXTBOOK";
}
