@startuml
!include ../../Style.puml

group add to EntryLog and get response

participant "backend:Backend" as Backend
participant "endpoint:entryEndpoint" as Endpoint
participant "entries:EntryLog" as EntryLog


Backend -> Endpoint : handleRequest(postReq)
Endpoint -> Endpoint : handlePost(postReq)
Endpoint -> EntryLog : addEntry(entry)
EntryLog -> EntryLog : add(entry)
EntryLog --> Endpoint
Endpoint -> Response ** : Response(CREATED, " ")
Response --> Endpoint
Endpoint --> Backend : reponse
end

@enduml