@startuml
!include ../../Style.puml

participant ":Frontend" as Frontend
participant ":Parser" as Parser
participant "command:DeleteCommand" as DeleteCommand
participant "requestGet:Request" as RequestGet
participant "requestDelete:Request" as RequestDelete
participant "backend:Backend" as Backend
participant "UI" as UI

activate Frontend
activate Parser
activate UI
Parser -> DeleteCommand ** : DeleteCommand(entryId)
activate DeleteCommand
return command

Frontend -> DeleteCommand :execute()
activate DeleteCommand
DeleteCommand -> RequestGet ** : Request(GET, entryId)
activate RequestGet
RequestGet --> DeleteCommand : requestGet
Destroy RequestGet
DeleteCommand -> Backend : requestEndpointEntry(requestGet)
ref over Backend
get Entry and get
responseGet
end ref
Backend --> DeleteCommand : responseGet

DeleteCommand -> RequestDelete ** : Request(DELETE, entryId)
activate RequestDelete
RequestDelete --> DeleteCommand
Destroy RequestDelete
DeleteCommand -> Backend : requestEndpointEntry(requestDelete)

ref over Backend
delete from EntryLog and
get responseDelete
end ref


Backend --> DeleteCommand : responseDelete
alt responseDelete.getResponseStatus() == ResponseStatus.NOT_FOUND
    DeleteCommand --> Parser : exception
else else
    DeleteCommand -> UI:printExpenditureDeleted(deletedEntry)
    UI --> DeleteCommand
    deactivate DeleteCommand
    destroy DeleteCommand
end
@enduml