@startuml
'https://plantuml.com/object-diagram
skinparam classAttributeIconSize 0
object SearchParser{
    - rawInput = "apple"
    - Inventory = inventory
    - searchType = Types.SearchType.KEYWORD
}

object SearchCommand{
    - rawInput = "apple"
    - Inventory = inventory
    - searchType = Types.SearchType.KEYWORD
}

SearchParser -> SearchCommand

@enduml
