@startuml
'https://plantuml.com/sequence-diagram

actor User
User -> ":EditParser" **:EditParser()
activate ":EditParser"
":EditParser" --> User
deactivate ":EditParser"

alt Contains "upc/" && User input length > 1
    User -> ":EditParser": run()
    activate ":EditParser"
    ":EditParser" -> ":EditCommand" **:EditCommand()
    activate ":EditCommand"
    ":EditCommand" --> ":EditParser"
    deactivate ":EditCommand"
    ":EditParser" -> ":EditCommand" : run()
    activate ":EditCommand"
    ":EditCommand" -> ":EditCommand": setEditInfo()
    activate ":EditCommand"
    ref over ":EditCommand" : Process User Edit Input
    ":EditCommand" --> ":EditCommand"
    deactivate ":EditCommand"
    ":EditCommand" --> ":EditParser"
    deactivate ":EditCommand"
    destroy ":EditCommand"
else else
    ":EditParser" -> ":EditParser": EditErrorException()
    activate ":EditParser"
    ":EditParser" -> "<<Class>>\nUI": printInvalidEditCommand()
    activate "<<Class>>\nUI"
    ref over "<<Class>>\nUI": Print Error Message
    "<<Class>>\nUI" --> ":EditParser"
    deactivate "<<Class>>\nUI"
    ":EditParser" --> ":EditParser"
    deactivate ":EditParser"
end

":EditParser" --> User
deactivate ":EditParser"
destroy ":EditParser"
@enduml