@startuml
'https://plantuml.com/sequence-diagram
title AlertParser Sequence Diagram

actor User
participant ":AlertParser"
User -> ":AlertParser" **

User -> ":AlertParser": run()
activate ":AlertParser"

alt rawInput == empty string
    ref over ":AlertParser"
        handle input error
    end
    ":AlertParser" --> User

end



alt rawInput == "add"

    ":AlertParser" -> ":AlertParser": parseAddAlert()
    activate ":AlertParser" #cyan
        opt incorrect format or exceeded quantity limit
            ref over ":AlertParser"
                handle input error
            end ref
        end

    ":AlertParser" --> User
        ref over ":AlertParser"
            add alert
        end ref
    return
 end


alt rawInput == "end"

    ":AlertParser" -> ":AlertParser": parseRemoveAlert()
     activate ":AlertParser" #cyan
        opt incorrect format or exceeded quantity limit
            ref over ":AlertParser"
                handle input error
            end ref
        end

    ":AlertParser" --> User
        ref over ":AlertParser"
            remove alert
        end ref
    return
end

alt rawInput == any other input
   ref over ":AlertParser"
    handle input error
    end ref
    ":AlertParser" --> User
end
return
destroy ":AlertParser"



@enduml