@startuml
object FilterParser{
    rawInput = "f/category perishables"
    Inventory = inventory
}
object FilterCommand{
    Inventory = inventory
    value = "perishables"
    filterMode = "f/category"
}
FilterParser -> FilterCommand
@enduml
