@startuml
'https://plantuml.com/sequence-diagram

participant ":Parser" as Parser
participant "command:AddCommand" as AddCommand
participant "entryObj:Entry" as Entry
participant "postReq:Request" as Request
participant "backend:Backend" as Backend
participant "endpoint:entryEndpoint" as Endpoint
participant "entries:EntryLog" as EntryLog
participant "reponse:Response" as Response
participant "UI" as UI

Parser -> AddCommand ** : AddCommand(description, price, category)
activate AddCommand
AddCommand -> Entry ** :Entry(description, price, category)
activate Entry
return entryObj
return command

-> AddCommand :execute()
activate AddCommand
AddCommand -> Request **
Request --> AddCommand : postReq
AddCommand --> Backend : requestEndpointEntry (postReq)
Backend -> Endpoint : handleRequest(postReq)
Endpoint -> Endpoint : handlePost(postReq)
Endpoint -> EntryLog : addEntry(entry)
EntryLog -> EntryLog : add(entry)
EntryLog --> Endpoint
Endpoint -> Response ** : Response(CREATED, " ")
Response --> Endpoint
Endpoint --> Backend : reponse
Backend --> AddCommand : reponse
alt response.getResponseStatus() == ResponseStatus.CREATED
    AddCommand -> UI : printExpenditureAdded(entryObj)
    UI --> AddCommand
else else
    AddCommand --> Parser : exception
        deactivate AddCommand
end





'Alice -> Bob: Authentication Request
'Bob --> Alice: Authentication Response
'
'Alice -> Bob: Another authentication Request
'Alice <-- Bob: another authentication Response


@enduml