@startuml
!include style.puml

Actor User as user USER_COLOR
Participant ":UI" as ui UI_COLOR
Participant ":RainyDay" as main #grey
Participant ":RainyDay" as main #grey
Participant ":Parser" as parser #black
Participant ":Command" as command COMMAND_COLOR
Participant ":Userdata" as userdata USERDATA_COLOR
Participant ":Storage" as storage STORAGE_COLOR

activate ui UI_COLOR
activate main #grey
user -[USER_COLOR]> ui : delete 1
ui --> main : :String
deactivate ui

main -> parser : parseUserInput(userInput:String)
activate parser #black

create command
parser -> command : new DeleteCommand
activate command COMMAND_COLOR

command --> parser : : DeleteCommand
deactivate command
parser --> main : : DeleteCommand
deactivate parser

main -> command : execute()
activate command COMMAND_COLOR
command -> userdata :deleteStatement\n(statementIndex:int)
activate userdata USERDATA_COLOR
userdata --> command
deactivate userdata
command --> main
deactivate command

main --> user

main -> storage : writeToFile(savedData:SavedData, filePath:String)
activate storage STORAGE_COLOR_T1
storage --> main
deactivate storage

@enduml