@startuml
!include <office/Concepts/globe_internet>
!include <office/Concepts/documents>
!include <office/Users/user>
!include style.puml

Package " "<<Rectangle>>{
    Class Ui UI_COLOR
    Class Command LOGIC_COLOR
    Class Storage STORAGE_COLOR
    Class Parser LOGIC_COLOR
    Class Data MODEL_COLOR
    Class Main #grey
}

Class "<$user>" as User MODEL_COLOR_T2
Class "<$documents>" as File UI_COLOR_T1


Ui -[#green]> Command
Ui -right[#green]-> Data
Parser -[#blue]-> Command
Command -[#blue]-> Storage
Command -down[#blue]-> Data
Main -[#grey]-> Ui
Main -[#grey]-> Parser
Main -[#grey]-> Storage
Main -up[#grey]-> Data


Storage -up[STORAGE_COLOR].> Data
Storage .right[STORAGE_COLOR].>File
User ..> Ui
@enduml