//@@author clement559
@startuml
!include Style.puml

actor User

box Manager COLOR_MAIN_LIGHT
participant ":ToDoListManager" as ToDoListManager COLOR_MAIN
end box

box Logic COLOR_LOGIC_LIGHT
participant ":Parser" as Parser COLOR_LOGIC
participant ":EditDeadlineCommand" as EditDeadlineCommand COLOR_LOGIC
end box

box TaskList COLOR_TASK_LIST_LIGHT
participant ":TaskList" as TaskList COLOR_TASK_LIST
participant ":Task" as Task COLOR_TASK_LIST
end box

box Ui COLOR_UI_LIGHT
participant ":Ui" as Ui COLOR_UI
end box

User -> ToDoListManager: input("due <id> -edit <deadline>")
ToDoListManager -> Parser: parseCommand(inputCommand)
Parser -> EditDeadlineCommand:
ToDoListManager -> EditDeadlineCommand: execute(taskList, ui)
EditDeadlineCommand -> TaskList: setDeadline(id, deadline)
TaskList -> TaskList: getTasks(id)
TaskList -> Task: setDeadline(deadline)
Task --> TaskList: taskString
TaskList -> Ui: printEditTaskMessage(taskString)
@enduml
