@startuml
'https://plantuml.com/sequence-diagram
!include Style.puml

participant ":EndWorkoutCommand" as end
participant ":WorkoutList" as list

activate end
activate list
-> end: execute()
end -> list: getCurrentWorkoutIndex()
list -> end: currentWorkoutIndex
alt no current workout
<- end: no ongoing workout message
else
end -> list: setCurrentWorkoutIndex(NO_CURRENT_WORKOUT)
<- end: end workout message
end
@enduml