@startuml
'https://plantuml.com/class-diagram

hide circle
hide member

class "EntryList" as entryList <<abstract>>

entryList *-left-> "1" ExpenseList

entryList *--> EntryXYZComparator
note left of EntryXYZComparator: EntryXYZComparatord = EntryAmountComparator, \nEntryDateComparator

entryList *-left-> "1" IncomeList

IncomeList -[hidden]down- ExpenseList


ExpenseList -right-> "*" Expense
IncomeList -right-> "*" Income


Expense -down-> "1" category
Income -down-> "1" category



@enduml