@startuml
!include Style.puml

actor User

box Manager COLOR_MAIN_LIGHT
participant ":ToDoListManager" as ToDoListManager COLOR_MAIN
end box

box Logic COLOR_LOGIC_LIGHT
participant ":Parser" as Parser COLOR_LOGIC
participant ":ExitCommand" as ExitCommand COLOR_LOGIC
end box

box Ui COLOR_UI_LIGHT
participant ":Ui" as Ui COLOR_UI
end box

box Storage COLOR_STORAGE_LIGHT
participant ":Storage" as Storage COLOR_STORAGE
endbox

User -> ToDoListManager: input("exit")
activate ToDoListManager
ToDoListManager -> Parser : parseCommand("exit")
activate Parser
create ExitCommand
Parser -> ExitCommand
activate ExitCommand
ExitCommand --> Parser:
deactivate ExitCommand
Parser --> ToDoListManager : command
deactivate Parser
ToDoListManager -> ExitCommand : execute(taskList, ui)
activate ExitCommand

ExitCommand -> Ui : printGoodbyeMessage()
activate Ui
Ui --> ExitCommand
deactivate Ui
ExitCommand --> ToDoListManager
deactivate ExitCommand
ToDoListManager -> Storage: saveData(taskList)
activate Storage
Storage --> ToDoListManager
deactivate Storage
ToDoListManager -> ExitCommand: shouldExit()
activate ExitCommand
ExitCommand --> ToDoListManager: true
deactivate ExitCommand
destroy ExitCommand
ToDoListManager --> User
deactivate ToDoListManager
destroy ToDoListManager
@enduml