@startuml
'https://plantuml.com/sequence-diagram

autonumber
actor User
participant ":Duke" as Duke

Duke -> Ui: getUserInput()
activate Duke
activate Ui
User -> Ui: User input
return User input
Duke -> Parser : processCommand(userInput)
activate Parser
Parser-> CalorieParser: CalorieParser(arguments)
activate CalorieParser
CalorieParser-> parseListCalorieCommand : parseListCalorieCommand(arguments)
activate parseListCalorieCommand
parseListCalorieCommand -> ListCalorieCommand : ListCalorieCommand()
activate ListCalorieCommand
return StringBuilder
return StringBuilder
return StringBuilder
return StringBuilder
@enduml