@startuml
!include Style.puml
hide members

class ToDoListManager COLOR_MAIN
class Ui COLOR_UI
package Logic <<Rectangle>> {
class Parser COLOR_LOGIC
class "{abstract}\nCommand" as Command COLOR_LOGIC
}
package "\t\t\t\tModel" <<Rectangle>> {
class TaskList COLOR_TASK_LIST
class Config COLOR_TASK_LIST
}
class Storage COLOR_STORAGE

ToDoListManager -l-> "1\t" Ui : creates >
ToDoListManager -u-> "\t1" Parser : creates >
ToDoListManager -d-> "\t\t1" TaskList : creates >
ToDoListManager -d-> "\t\t1" Config : creates >
ToDoListManager -d-> "1" Storage : creates\t >
ToDoListManager .d.> Command : executes >
Parser .r.> Command
Storage .u.> TaskList
Storage .u.> Config
@enduml