@startuml
!include style.puml
hide empty members

package Model <<Rectangle>>{
    class Task COLOR_TASK_LIST {
        -id: int
        -description: String
        -email: String = null
        -deadline: LocalDateTime = null
        -repeatTimes: int
        -tags: TreeSet<String>
    }
    class "<<enumeration>>\nPriority" as Priority COLOR_TASK_LIST {
        HIGH
        MEDIUM
        LOW
        NONE
    }
    class TaskList COLOR_TASK_LIST
    class Config COLOR_TASK_LIST {
        -repeatFrequency: int
        -checkFrequency: int
        -lastChecked: LocalDateTime
    }
}

TaskList ..> Priority
Task -r-> "1" Priority
TaskList *-d-> "*" Task
@enduml
