@startuml
!include Style.puml

actor User

box Manager COLOR_MAIN_LIGHT
participant ":ToDoListManager" as ToDoListManager COLOR_MAIN
end box

box Logic COLOR_LOGIC_LIGHT
participant ":Parser" as Parser COLOR_LOGIC
participant ":ResetCommand" as ResetCommand COLOR_LOGIC
end box

box TaskList COLOR_TASK_LIST_LIGHT
participant ":TaskList" as TaskList COLOR_TASK_LIST
end box

box Ui COLOR_UI_LIGHT
participant ":Ui" as Ui COLOR_UI
end box

User -> ToDoListManager: input("reset")
ToDoListManager -> Parser : parseCommand(input command)
create ResetCommand
Parser -> ResetCommand :  ResetCommand()
Parser --> ToDoListManager : command
ToDoListManager -> ResetCommand : execute(taskList, config, ui)
alt getUserConfirmation() = true
ResetCommand -> TaskList : taskList.reset();
ResetCommand -> Ui : printResetMessage(true);
else
ResetCommand -> Ui : printResetMessage(false);
end
@enduml