@startuml
participant ":Parser" as Parser
participant ":SetBudgetCommand" as SetBudgetCommand
participant ":UserData" as UserData

[-> Parser : parseUserInput(userInput)
activate Parser
Parser -> Parser : setUserBudgetGoal(userInput)
activate Parser
create SetBudgetCommand
Parser -> SetBudgetCommand
activate SetBudgetCommand
SetBudgetCommand --> Parser : :SetBudgetCommand
deactivate SetBudgetCommand
Parser --> Parser : :SetBudgetCommand
deactivate Parser
Parser -->[ : :SetBudgetCommand

deactivate Parser
[-> SetBudgetCommand : execute()
activate SetBudgetCommand
activate UserData
SetBudgetCommand -> UserData : setBudgetGoal(goal)
UserData --> SetBudgetCommand
deactivate UserData
SetBudgetCommand -->[ : :CommandResult(output)

@enduml
