@startuml
participant ":ShortcutDeleteCommand" as ShortcutDeleteCommand
participant "shortcutCommands:HashMap" as shortcutCommands

[-> ShortcutDeleteCommand : execute()
activate ShortcutDeleteCommand

ShortcutDeleteCommand -> shortcutCommands : containsKey(key)
activate shortcutCommands
shortcutCommands --> ShortcutDeleteCommand

deactivate shortcutCommands


opt contains key


ShortcutDeleteCommand -> shortcutCommands : remove(key, value)
activate shortcutCommands
shortcutCommands --> ShortcutDeleteCommand

deactivate shortcutCommands

end
[<--ShortcutDeleteCommand
deactivate ShortcutDeleteCommand
ShortcutDeleteCommand <-[hidden]- ShortcutDeleteCommand
'Hidden arrow to position the destroy marker below the end of the activation bar.
destroy ShortcutDeleteCommand

@enduml