//@@author jeromeongithub
@startuml
!include Style.puml

actor User

participant ":Main" as Main

box Manager COLOR_MAIN_LIGHT
participant ":ToDoListManager" as ToDoListManager COLOR_MAIN
end box

box Storage COLOR_STORAGE_LIGHT
participant ":Storage" as Storage COLOR_STORAGE
end box

box Ui COLOR_UI_LIGHT
participant ":Ui" as Ui COLOR_UI

User -> Main: start program
Main -> ToDoListManager
activate ToDoListManager
ToDoListManager -> Storage: loadData()
activate Storage
Storage --> ToDoListManager
deactivate Storage
ToDoListManager -> Ui: printNewSaveMessage()
activate Ui
Ui --> ToDoListManager
deactivate Ui
ToDoListManager --> User
deactivate ToDoListManager
@enduml

