@startuml
'https://plantuml.com/sequence-diagram

participant "Text File" as Text
participant ":Storage" as Storage
participant ":EntryLog" as EntryLog

Text -> Storage: readFromDatabase()
Storage -> EntryLog: readFromDatabase()
EntryLog -> Storage: writeToDatabase(entryLog.getEntriesList())
Text <- Storage: writeToDatabase(entryLog.getEntriesList())

@enduml