@startuml
!include Style.puml

box Manager COLOR_MAIN_LIGHT
participant ":ToDoListManager" as ToDoListManager COLOR_MAIN
end box

box Ui COLOR_UI_LIGHT
participant ":Ui" as Ui COLOR_UI
end box

box Storage COLOR_STORAGE_LIGHT
participant ":Storage" as Storage COLOR_STORAGE
end box

box TaskList COLOR_TASK_LIST_LIGHT
participant ":TaskList" as TaskList1 COLOR_TASK_LIST
participant ":TaskList" as TaskList2 COLOR_TASK_LIST
end box

activate ToDoListManager

ToDoListManager -> Ui:printWelcomeMessage()
activate Ui
Ui --> ToDoListManager
deactivate Ui

ToDoListManager -> Storage:isNewSave()
activate Storage
Storage --> ToDoListManager
deactivate Storage

alt storage.isNewSave()
    ToDoListManager -> Ui:printNewSaveMessage()
    activate Ui
    Ui --> ToDoListManager
    deactivate Ui
else else
    ToDoListManager -> Storage:loadData()
    activate Storage

    create TaskList2
    Storage -> TaskList2
    activate TaskList2
    TaskList2 --> Storage
    deactivate TaskList2
    destroy TaskList1

    ToDoListManager <-- Storage:taskList
    deactivate Storage

    ToDoListManager -> Ui:printLoadSaveMessage()
    activate Ui
    Ui --> ToDoListManager
    deactivate Ui
end
@enduml