!define RED #FF0000FF
!define ORANGE #FF8000FF
!define YELLOW #FFFF00FF
!define CHARTREUSE #80FF00FF
!define GREEN #00FF00FF
!define SPRING_GREEN #00FF80FF
!define CYAN #00FFFFFF
!define AZURE #0080FFFF
!define BLUE #0000FFFF
!define VIOLET #8000FFFF
!define MAGENTA #FF00FFFF
!define ROSE #FF0080FF