@startuml
!include Style.puml
skinparam classAttributeIconSize 0

class Main {
    - commandParser: CommandParser
    - storage: Storage
    + Main()
    + run()
    + runCommandTillExit()
}

class Ui {
    - in: Scanner
    + getUserInput(): String
    + showWelcomeMessage()
    + showEndingMessage()
    + showHelpMessage()
    + addPetCommandMessage(String petName)
}

note bottom: Not all methods are included here

package VariousCommands <<Rectangle>> {
}

Main -> Ui
VariousCommands-[dashed]left-> Ui : uses >

@enduml