@startuml
participant ":ViewCommand" as ViewCommand
participant ":UserData" as UserData
participant ":ViewResult" as ViewResult

[-> ViewCommand : execute()
activate ViewCommand

loop sizeOfFinancialReport
    ViewCommand -> UserData : getStatement(i)
    activate UserData
    UserData --> ViewCommand: FinancialStatement[i]
    deactivate UserData
    end
        opt sortingRequired
        ViewCommand -> ViewCommand : sortByValue
    end

    ViewCommand -> ViewResult : printReport(validIndexes : arrayList<Integer>)
    activate ViewResult

ViewResult ->] : Print Table Header to User
loop sizeOfArrayList
    ViewResult -> UserData : getStatement(i)
    activate UserData
    UserData --> ViewResult: FinancialStatement[i]
    deactivate UserData
    ViewResult -> ViewResult : Convert to Valid String
    ViewResult ->] : Print Statement to User
    end
    ViewResult ->] : Print Summary to User
    ViewResult --> ViewCommand
    deactivate ViewResult

ViewCommand -->[ : null
deactivate ViewCommand
ViewCommand <-[hidden]- ViewCommand
'Hidden arrow to position the destroy marker below the end of the activation bar.
destroy ViewCommand
@enduml