@startuml
!include ../../Style.puml

mainframe sd Endpoint /entry - Handle POST
participant ":EntryEndpoint" as EntryEndpoint
participant ":EntryLog" as EntryLog

-> EntryEndpoint : handlePost(Request)

group opt [Invalid description or amount]
    <-- EntryEndpoint: Response(UNPROCESSABLE_CONTENT)
end group

EntryEndpoint -> EntryLog : addEntry()
return

<-- EntryEndpoint : Response(CREATED)
@enduml