@startuml
'https://plantuml.com/sequence-diagram

participant ":RestockParser"
":RestockParser" -> ":RestockCommand" **
activate ":RestockCommand"
":RestockCommand" --> ":RestockParser"
deactivate ":RestockCommand"
":RestockParser" -> ":RestockCommand": run()
activate ":RestockCommand"
":RestockCommand"->":RestockCommand": restockItem()
group sd Increase Quantity of the Item
activate ":RestockCommand" #Cyan
ref over ":RestockCommand": Retrieve Item from \n Hashmap and keep \n track of previous Quantity Value.
":RestockCommand" -> ":RestockCommand": checkRestockCommandLength()
activate ":RestockCommand" #Red

alt Command Length != 2
ref over ":RestockCommand": Handle Missing Parameters \n Exception
end


activate ":RestockCommand"
":RestockCommand" --> ":RestockCommand"
deactivate ":RestockCommand"
":RestockCommand" -> ":RestockCommand": updateItemQuantity()
activate ":RestockCommand" #Green


ref over ":RestockCommand"
Update the Quantity of Item if user input is valid
end


":RestockCommand" --> ":RestockCommand"
deactivate ":RestockCommand"


":RestockCommand"->":RestockCommand": handleTrie()
activate ":RestockCommand" #Green
ref over ":RestockCommand": Update Inventory Data Structure
":RestockCommand"-->":RestockCommand"
deactivate ":RestockCommand"


alt Valid Inputs
":RestockCommand" -> "<<Class>>\nUI": printRestockDetails()
activate "<<Class>>\nUI"
ref over "<<Class>>\nUI": Print Restock Message
"<<Class>>\nUI" -->":RestockCommand"
deactivate "<<Class>>\nUI"
else Item Does Not Exist
":RestockCommand" -> "<<Class>>\nUI": printItemNotFound()
activate "<<Class>>\nUI"
ref over "<<Class>>\nUI": Print Error Message
"<<Class>>\nUI"-->":RestockCommand"
deactivate "<<Class>>\nUI"
else Missing Input Parameters
":RestockCommand" -> "<<Class>>\nUI": printInvalidRestockCommand()
activate "<<Class>>\nUI"
ref over "<<Class>>\nUI": Print Error Message
"<<Class>>\nUI"-->":RestockCommand"
deactivate "<<Class>>\nUI"
else Invalid Input Parameters
":RestockCommand" -> "<<Class>>\nUI": printInvalidAddQuantityInput()
activate "<<Class>>\nUI"
ref over "<<Class>>\nUI": Print Error Message
"<<Class>>\nUI"-->":RestockCommand"
deactivate "<<Class>>\nUI"
end
":RestockCommand" -> "<<Class>>\nSessionManager": writeSession()
activate "<<Class>>\nSessionManager"
ref over "<<Class>>\nSessionManager": Update CSV File
"<<Class>>\nSessionManager" --> ":RestockCommand"
deactivate "<<Class>>\nSessionManager"
":RestockCommand" --> ":RestockCommand"
deactivate ":RestockCommand"
end
":RestockCommand" --> ":RestockParser"
destroy ":RestockCommand"
@enduml