@startuml
'https://plantuml.com/sequence-diagram
actor User
participant ":RestockParser"
User -> ":RestockParser" **:RestockParser()
activate ":RestockParser"
":RestockParser" --> User
deactivate ":RestockParser"
User->":RestockParser":run()
activate ":RestockParser"
":RestockParser" -> ":RestockCommand" **:RestockCommand()
activate ":RestockCommand"
":RestockCommand" --> ":RestockParser"
deactivate ":RestockCommand"


alt Contains "upc/" and input length > 1
    ":RestockParser"->":RestockCommand": run()
    activate ":RestockCommand"
    ref over ":RestockCommand","<<Class>>\nUI": Increases quantity of the Item
    ":RestockCommand"-->":RestockParser":
    deactivate ":RestockCommand"
    ":RestockParser"-->User:
    destroy ":RestockCommand"


else No "upc/" or input length <= 1
    ":RestockParser"->":RestockParser": EditErrorException()
    activate ":RestockParser"
    ":RestockParser"->"<<Class>>\nUI":printInvalidSellCommand()
    activate "<<Class>>\nUI"
    "<<Class>>\nUI"-->":RestockParser":
    deactivate "<<Class>>\nUI"
    ":RestockParser"-->":RestockParser":
    deactivate ":RestockParser"
    ":RestockParser"-->User:
    deactivate ":RestockParser"
end


deactivate ":RestockParser"
destroy ":RestockParser"
@enduml