@startuml
!include ../../Style.puml
scale 1.3
hide members
class Frontend #90C4EA
class Backend #BDEA9E
class UI #EF7DE5
class Parser
class ParseXYZCommand
class "{abstract}\nParseCommand"
class XYZCommand #EFC1C1
note left: XYZCommand = AddCommand,\nDeleteCommand,ViewCommand, etc.

Frontend ..> Parser
Frontend -left-> Backend
Frontend -> UI
Parser ..> ParseXYZCommand : creates >
ParseXYZCommand .right.|> "{abstract}\nParseCommand"
ParseXYZCommand ..> XYZCommand : returns >
XYZCommand .up.> Backend : executed by >






@enduml