@startuml
!include ../../Style.puml
hide members
class Parser

scale 1.2
class ParseXYZCommand
class "{abstract}\nParseCommand"
class XYZCommand
note left: XYZCommand = AddCommand,\nDeleteCommand,ViewCommand, etc.

Parser ..> ParseXYZCommand : creates >
ParseXYZCommand .up.|> "{abstract}\nParseCommand"
ParseXYZCommand ..> XYZCommand : returns >






@enduml