@startuml
'https://plantuml.com/sequence-diagram

participant ":CategoryParser"

skinparam style strictuml
group sd [execute command by categoryCommandType]
     ":CategoryParser" -> ":CategoryCommand"**: run()
     participant "Ui" <<class>>
     activate ":CategoryCommand"
     alt if categoryCommandType is 'list'
        ":CategoryCommand" -> Ui: listAllCategories()
        activate ":CategoryCommand" #cyan
        ref over Ui
            print list of categories in inventory
        end ref
        return
        destroy Ui
        return
     else if categoryCommandType is 'table'
        ":CategoryCommand" -> Ui: listCategoryAndItems()
        activate ":CategoryCommand" #cyan
        ref over Ui
            print table of categories and all items in each category
        end ref
        return
        destroy Ui
        deactivate ":CategoryCommand" #cyan
        ":CategoryCommand" --> ":CategoryParser"
        destroy ":CategoryCommand"
     end

end
@enduml