package seedu.apollo.module;

public enum LessonType {
    LECTURE,
    PACKAGED_LECTURE,
    SECTIONAL_TEACHING,
    DESIGN_LECTURE,
    TUTORIAL,
    PACKAGED_TUTORIAL,
    RECITATION,
    LABORATORY,
    WORKSHOP,
    SEMINAR_STYLE_MODULE_CLASS,
    MINI_PROJECT,
    TUTORIAL_TYPE_2,

}
