@startuml
!include ../Style.puml

mainframe sd Endpoint /entries - Handle DELETE
participant ":EntryEndpoint" as EntryEndpoint
participant ":EntryLog" as EntryLog
participant ":Entry" as Entry


-> EntryEndpoint : handleDelete(Request)
EntryEndpoint -> EntryLog : deleteEntry()
activate Entry

group opt
    EntryEndpoint <-- EntryLog : IndexOutOfBoundsException
    <-- EntryEndpoint : Response(NOT_FOUND)
end

EntryEndpoint <-- EntryLog : Entry
destroy Entry

<-- EntryEndpoint : Response(OK)
@enduml