@startuml
!include ../Style.puml

mainframe sd Endpoint /entry - Handle PATCH

-> EntryEndpoint : handlePatch(Request)

EntryEndpoint -> EntryLog : getEntry()
EntryEndpoint <-- EntryLog : Entry
group opt [Entry is null]
    <-- EntryEndpoint : Response(NOT_FOUND)
end

group opt [Edit category]
    EntryEndpoint -> Entry : setCategory()

    group opt [Category is invalid]
        EntryEndpoint <-- Entry : InvalidCategoryException
        <-- EntryEndpoint : Response(UNPROCESSABLE_CONTENT)
    end
    EntryEndpoint <-- Entry
end

group opt [Edit amount]
    EntryEndpoint -> Entry : setAmount()
    EntryEndpoint <-- Entry
end

group opt [Edit description]
    EntryEndpoint -> Entry : setDescription()
    EntryEndpoint <-- Entry
end

<-- EntryEndpoint : Response(OK)
@enduml