@startuml
!include ../Style.puml

mainframe sd Endpoint /entry - Handle POST

-> EntryEndpoint : handlePost(Request)

EntryEndpoint -> EntryLog : addEntry()
return

<-- EntryEndpoint : Response(CREATED)
@enduml