@startuml
'https://plantuml.com/object-diagram

skinparam classAttributeIconSize 0
object ListParser{
    - Inventory = inventory
}

object ListCommand{
    - Inventory = inventory
}

ListParser -> ListCommand
@enduml
