@startuml
!define AWSPUML https://cdn.rawgit.com/Willibaur/PlantUML_AWS/07362bc9/
skinparam defaultTextAlignment center
!define ICONURLAWSPUML https://raw.githubusercontent.com/Willibaur/PlantUML_AWS/07362bc9/
!define AWSPUML_SPRITESURL https://raw.githubusercontent.com/rabelenda/cicon-plantuml-sprites/v2.0/
!define AWSPUML_NOBORDER
skinparam defaultFontSize 24

participant ":MainInputParser" as MainInputParser
-> MainInputParser: parseInput(line)
activate MainInputParser

participant ":ExitCommand" as ExitCommand
alt Command is "exit"
MainInputParser->ExitCommand** : <<create>>
activate ExitCommand
return
deactivate ExitCommand
destroy ExitCommand

else Command is "help"
participant ":HelpCommand" as HelpCommand
MainInputParser->HelpCommand** : <<create>>
activate HelpCommand
return
deactivate HelpCommand
destroy HelpCommand

else Command is "delete"
participant ":ParseDelete" as ParseDelete
MainInputParser->ParseDelete** : ParseDelete(splitValues[INDEX_USERSTRING])
activate ParseDelete

participant ":ParseIndividualValue" as ParseIndividualValue
ParseDelete->ParseIndividualValue : parseIndividualValue(userInput,BLANK,BLANK)
activate ParseIndividualValue
return details:String
ParseDelete-->MainInputParser
destroy ParseDelete
deactivate ParseDelete
deactivate ParseIndividualValue
else Command is one of the add expenditure keywords
participant ":ParseAdd" as ParseAdd
MainInputParser->ParseAdd** :parseIndividualValue(splitValues[INDEX_USERSTRING])
activate ParseAdd
loop three times to extract user fields
ParseAdd->ParseIndividualValue : parseIndividualValue
activate ParseIndividualValue
return :String
deactivate ParseIndividualValue
end
alt Command is "Academic"
participant ":AcademicExpenditureCommand" as AcademicExpenditureCommand
ParseAdd->AcademicExpenditureCommand** : AcademicExpenditureCommand(descriptionVal, amount, date)
activate AcademicExpenditureCommand
return
deactivate AcademicExpenditureCommand
destroy AcademicExpenditureCommand
else Command is "Food"
participant ":FoodExpenditureCommand" as FoodExpenditureCommand
ParseAdd-> FoodExpenditureCommand** : FoodExpenditureCommand(descriptionVal, amount, date)
activate FoodExpenditureCommand
return
deactivate FoodExpenditureCommand
destroy FoodExpenditureCommand
end

ParseAdd --> MainInputParser
destroy ParseAdd
deactivate ParseAdd

else Command is "list"
participant ":ListCommand" as ListCommand
MainInputParser->ListCommand** : <<create>>
activate ListCommand
return
deactivate ListCommand
destroy ListCommand

else Command is "lend" or "borrow"
participant ":ParseLendBorrow" as ParseLendBorrow
MainInputParser->ParseLendBorrow** : ParseLendBorrow(splitValues[INDEX_USERSTRING])
activate ParseLendBorrow
loop five times to extract user fields
ParseLendBorrow->ParseIndividualValue : parseIndividualValue
activate ParseIndividualValue
return :String
deactivate ParseIndividualValue
end
alt Command is "Lend"
participant ":LendExpenditureCommand" as LendExpenditureCommand
ParseLendBorrow->LendExpenditureCommand** : LendExpenditureCommand
activate LendExpenditureCommand
return
deactivate LendExpenditureCommand
destroy LendExpenditureCommand
else Command is "Borrow"
participant ":BorrowExpenditureCommand" as BorrowExpenditureCommand
ParseLendBorrow-> BorrowExpenditureCommand** : BorrowExpenditureCommand
activate BorrowExpenditureCommand
return
deactivate BorrowExpenditureCommand
destroy BorrowExpenditureCommand
end
ParseLendBorrow --> MainInputParser
destroy ParseLendBorrow
end
@enduml