@startuml ArchitectureInteract
box Manager #White
Actor User #Blue
participant ":UI" as UI #Gray
participant ":Duke" as Duke #Gold
participant ":Parser" as Parser #Yellow
participant ":Command" as Command #Beige
participant ":RecipeList" as RecipeList #OrangeRed
participant ":Storage" as Storage #DimGray
end box

activate Duke #Gold
Duke -> UI : readCommand()
activate UI #Gray
User -> UI : "delete 1"
UI --> Duke : "delete 1"
Duke -> Parser : parseCommand()
activate Parser #Yellow
Parser --> Duke
deactivate Parser
Duke -> Command : execute()
activate Command #Beige
Command -> RecipeList : removeRecipe()
activate RecipeList #OrangeRed
RecipeList --> Command
deactivate RecipeList
Command -> UI : showRecipeDeleted()
Command -> Storage : writeSavedFile()
activate Storage #DimGray
loop number of recipes times
Storage -> Storage : write()
activate Storage #DimGray
Storage --> Storage
deactivate Storage
end loop
Storage --> Command
deactivate Storage
Command --> Duke
deactivate Command
@enduml