@startuml Recipe Find
box Find #White
Actor User
participant ":UI" as UI #Gray
participant ":Duke" as Duke #Gold
participant ":Parser" as Parser #Yellow
participant ":Command" as Command #Beige
participant ":RecipeList" as RecipeList #OrangeRed
end box

activate Duke #Gold
Duke -> UI : readCommand()
activate UI #Gray
User -> UI : "Find MaLaXiangGuo"
UI --> Duke : "Find MaLaXiangGuo"
deactivate UI
Duke -> Parser : parseCommand()
activate Parser #Yellow
Parser --> Duke
deactivate Parser
Duke -> Command : execute()
activate Command #Beige
Command -> RecipeList : searchRecipeList()
activate RecipeList #OrangeRed
RecipeList -> User : show recipe with index
RecipeList --> Command
deactivate RecipeList
Command --> Duke
deactivate Command


@enduml