@startuml Help
box Help #White
Actor User
participant ":UI" as UI #Gray
participant ":Duke" as Duke #Gold
participant ":Parser" as Parser #Yellow
participant ":Command" as Command1 #Beige
end box

activate Duke #Gold
Duke -> UI : readCommand()
activate UI #Gray
User -> UI : "help"
UI --> Duke : "help"
Duke -> Parser : parseCommand()
activate Parser #Yellow
Parser --> Duke
deactivate Parser
Duke -> Command1 : execute()
activate Command1 #Beige
Command1 -> UI : showHelp()
UI -> User : help message shown
UI --> Command1
deactivate UI
Command1 --> Duke
deactivate Command1
Duke -> Command1 : delete
destroy Command1


@enduml