@startuml Help
box Help #White
Actor User
participant ":UI" as UI #Gray
participant ":Duke" as Duke #Gold
participant ":Parser" as Parser #Yellow
participant ":Command" as Command #Beige
end box

activate Duke #Gold
Duke -> UI : readCommand()
activate UI #Gray
User -> UI : "help"
UI --> Duke : "help"
deactivate UI
Duke -> Parser : parseCommand()
activate Parser #Yellow
Parser --> Duke
deactivate Parser
Duke -> Command : execute()
activate Command #Beige
Command -> UI : showHelp()
activate UI #Gray
UI -> User : help message
UI --> Command
deactivate UI
Command --> Duke
Duke -> Command : delete
deactivate Command
destroy Command


@enduml