@startuml MainArchitecture 

archimate #Technology "User" as User <<technology-device>>
archimate #Technology "Data" as Data <<application-data-object>>


rectangle RM {
    rectangle UI 
    rectangle Duke 
    rectangle Parser 
    rectangle Storage 
    rectangle RecipeList
    User -down-> UI
    Storage -> Data
    Duke -up-> UI
    Duke -> Storage
    Storage -up-> RecipeList
    Duke -> RecipeList
}
@enduml
