@startuml
hide footbox
title Add Dish Sequence Diagram

box "AddDishCommand"
participant ":AddDishCommand" as AddDishCommand
endbox

box "DishManager"
participant ":DishManager" as DishManager
endbox

box "Dish"
participant ":Dish" as Dish
endbox

-> AddDishCommand: execute("dish name", price, ["ingredient 1", "ingredient 2", ...])
activate AddDishCommand
AddDishCommand -> DishManager ++ : addDish("dish name", price, ["ingredient 1", "ingredient 2", ...])

create Dish
Dish <- DishManager ++ : create new Dish("dish name", price, ["ingredient 1", "ingredient 2", ...])
Dish --> DishManager
deactivate
AddDishCommand <-- DishManager
deactivate
<-- AddDishCommand:

destroy AddDishCommand
|||
@enduml