@startuml
!include Style.puml
title Add Meeting Sequence Diagram
box "AddMeetingCommand"
participant ":AddMeetingCommand" as AddMeetingCommand
endbox

box "Meeting"
participant ":Meeting" as Meeting
endbox

box "MeetingManager"
participant ":MeetingManager" as MeetingManager
endbox


->AddMeetingCommand:execute(ui)
Activate AddMeetingCommand

create Meeting
AddMeetingCommand->Meeting++:m=new Meeting(time,issue)
Meeting-->AddMeetingCommand

AddMeetingCommand->MeetingManager:addMeeting(m,ui)
Activate MeetingManager
MeetingManager-->AddMeetingCommand


@enduml