@startuml
title Add Meeting Sequence Diagram
box "AddMeetingCommand"
participant ":AddMeetingCommand" as AddMeetingCommand
endbox

box "Meeting"
participant ":Meeting" as Meeting
endbox

box "MeetingManager"
participant ":MeetingManager" as MeetingManager
endbox

Activate AddMeetingCommand
->AddMeetingCommand:AddMeetingCommand(time,issue)
->AddMeetingCommand:execute(ui)


create Meeting
AddMeetingCommand->Meeting++:m=new Meeting(time,issue)
Meeting-->AddMeetingCommand

AddMeetingCommand->MeetingManager:addMeeting(m,ui)
Activate MeetingManager
MeetingManager-->AddMeetingCommand

<-- AddMeetingCommand: ui.printMessage("Meeting added")
@enduml