@startuml
PlannerCommandHandler->UserPlan : addPlan()
activate UserPlan
UserPlan -> "newPlan:Plan" **
activate "newPlan:Plan"
"newPlan:Plan" --> UserPlan
deactivate "newPlan:Plan"
activate Storage
UserPlan -> Storage : writeToJson()
Storage --> UserPlan
deactivate Storage
deactivate UserPlan
@enduml