@startuml
hidefootbox
PlannerCommandHandler->UserPlan : addPlan()
activate UserPlan
UserPlan -> "newPlan:Plan" **
activate "newPlan:Plan"
"newPlan:Plan" --> UserPlan
deactivate "newPlan:Plan"
UserPlan -> Storage : writeToJson()
activate Storage
Storage --> UserPlan
deactivate Storage
deactivate UserPlan
@enduml