@startuml
!include Style.puml
left to right direction
skinparam componentStyle rectangle

component userInput

component EveNtUS {
component main COLOR1
component Parser COLOR1
component Ui COLOR1
component Command COLOR1
component Storage COLOR1
component Parser COLOR1
}

component "textFile"

[userInput]..>[Ui]
[Ui]-->[main]
[main]-->[Storage]
[textFile]..>[Storage]
[main]-->[Command]
[main]->[Ui]
[main]->[Parser]
[Parser]-->[main]
[Command]..>[main]
[Storage]-->[textFile]
@enduml