@startuml
autoactivate on

participant ":AddCardToTagCommand" as AddCardToTagCommand
participant ":TagList" as TagList
participant ":CardList" as CardList
participant ":CardSelector" as CardSelector
participant ":TagSelector" as TagSelector
participant ":TagList" as TagList
participant ":DeckList" as DeckList
participant ":Tag" as Tag
participant ":Card" as Card
participant ":UserInterface" as UserInterface


Create AddCardToTagCommand
CardKeywordParser -> AddCardToTagCommand : AddCardToTagCommand()
activate AddCardToTagCommand

Create CardSelector
AddCardToTagCommand -> CardSelector : CardSelector()
return

Create TagSelector
AddCardToTagCommand -> TagSelector : TagSelector()
return

AddCardToTagCommand -> AddCardToTagCommand: execute()
AddCardToTagCommand -> CardList : findCard(cardSelector)

alt index is specified
CardList -> CardSelector : getIndex()
return cardIndex
else uuid is specified
CardList -> CardSelector : getUUID()
return cardUUID
end
return cardAffected

AddCardToTagCommand -> TagList : findTag(tagSelector)

alt index is specified
TagList -> TagSelector : getIndex()
return tagIndex
else tagName is specified
TagList -> TagSelector : getTagName()
return tagUUID
end
return tagToAdd

AddCardToTagCommand -> AddCardToTagCommand : AddCardToTag(cardToAdd)
opt cardAffected.getUUID() != null
AddCardToTagCommand -> Card : getUUID()
return cardUUID
AddCardToTagCommand -> Tag : removeCard(carUUID)
return
AddCardToTagCommand -> Tag : getUUID()
return tagUUID
AddCardToTagCommand -> Card : removeTag(tagUUID)
return

end
return

AddCardToTagCommand -> UserInterface : printRemoveTagFromCard()
return


@enduml
