@startuml
autoactivate on

participant ":RemoveTagFromCardCommand" as RemoveTagFromCardCommand
participant ":TagList" as TagList
participant ":CardList" as CardList
participant ":CardSelector" as CardSelector
participant ":TagSelector" as TagSelector
participant ":TagList" as TagList
participant ":DeckList" as DeckList
participant ":Tag" as Tag
participant ":Card" as Card
participant ":UserInterface" as UserInterface


Create RemoveTagFromCardCommand
CardKeywordParser -> RemoveTagFromCardCommand : RemoveTagFromCardCommand()
activate RemoveTagFromCardCommand

Create CardSelector
RemoveTagFromCardCommand -> CardSelector : CardSelector()
return

Create TagSelector
RemoveTagFromCardCommand -> TagSelector : TagSelector()
return

RemoveTagFromCardCommand -> RemoveTagFromCardCommand: execute()
RemoveTagFromCardCommand -> CardList : findCard(cardSelector)

alt index is specified
CardList -> CardSelector : getIndex()
return cardIndex
else uuid is specified
CardList -> CardSelector : getUUID()
return cardUUID
end
return cardAffected


RemoveTagFromCardCommand -> TagList : findTag(tagSelector)

alt index is specified
TagList -> TagSelector : getIndex()
return tagIndex
else tagName is specified
TagList -> TagSelector : getTagName()
return tagUUID
end
return tagToRemove

RemoveTagFromCardCommand -> RemoveTagFromCardCommand : RemoveTagFromCard(cardAffected, tagToRemove)
opt cardAffected.getUUID() != null
RemoveTagFromCardCommand -> Card : getUUID()
return cardUUID
RemoveTagFromCardCommand -> Tag : removeCard(carUUID)
return
RemoveTagFromCardCommand -> Tag : getUUID()
return tagUUID
RemoveTagFromCardCommand -> Card : removeTag(tagUUID)
return

end
return

RemoveTagFromCardCommand -> UserInterface : printRemoveTagFromCard()
return

@enduml
