@startuml
'https://plantuml.com/sequence-diagram

hide footbox

-> ":ChooseVenueCommand": execute()

activate ":ChooseVenueCommand"

":ChooseVenueCommand" -> ":Event": updateVenue()
activate ":Event"
":Event" -> ":VenueList": getVenue()
activate ":VenueList"
":VenueList" --> ":Event": Venue
deactivate ":VenueList"
":Event" -> ":Ui": showVenueSelectionMessage()
activate ":Ui"
":Ui" --> ":Event":
deactivate ":Ui"
":Event" --> ":ChooseVenueCommand":
deactivate ":Event"

":ChooseVenueCommand" -> "<<class>>\nEventDetailsStorage": updateFile()
activate "<<class>>\nEventDetailsStorage"
"<<class>>\nEventDetailsStorage" --> ":ChooseVenueCommand":

deactivate "<<class>>\nEventDetailsStorage"
<-- ":ChooseVenueCommand"

deactivate ":ChooseVenueCommand"

destroy ":ChooseVenueCommand"
@enduml