@startuml
!define DINERDIRECTOR_COLOR #yellow
!define PARSER_COLOR #orange
!define COMMAND_COLOR #purple
!define UI_COLOR #lightgreen
!define MANAGER_COLOR #lime
!define ENTITY_COLOR #darkgreen
!define STORAGE_COLOR #pink

@enduml
