@startuml
skinparam classAttributeIconSize 0
hide circle
!include style.puml

interface CommandList <<interface>> STORAGE_COLOUR

class GeneralCommandHandler LOGIC_COLOUR {

+ handleGeneralUserCommands(userCommands: String[], ui: Ui, exerciseGenerator: GenerateExercise, userCareerData: UserCareerData, exerciseStateHandler: ExerciseStateHandler ,storage: Storage, planner: UserPlan, achievementListHandler: AchievementListHandler, scanner: Scanner): void
}

class PlannerCommandHandler LOGIC_COLOUR {
+ plannerCommandHandler (ui: Ui, planner: UserPlan, storage: Storage, in: Scanner): void
}

class ExerciseSessionCommandHandler LOGIC_COLOUR {
+ handleExerciseSessionUserCommands (userCommands: String[], ui: Ui, userCareerData: UserCareerData, exerciseStateHandler: ExerciseStateHandler, achievementListHandler: AchievementListHandler): void
+ confirmExitDuringWorkout(): boolean
}

CommandList <|-- GeneralCommandHandler
CommandList <|-- ExerciseSessionCommandHandler
CommandList <|-- PlannerCommandHandler

@enduml