@startuml
'https://plantuml.com/sequence-diagram

hide footbox

 -> ":CompanyListDecoder": read()
     activate ":CompanyListDecoder"
        ":CompanyListDecoder" -> ":Storage" :checkFileAccess(filePath)
        activate ":Storage"
        ":Storage" --> ":CompanyListDecoder"
        ":CompanyListDecoder" -> "f:File" :(filePath)
        activate "f:File"
            "f:File" --> ":CompanyListDecoder"
        ":CompanyListDecoder" -> "s:Scanner"
        activate "s:Scanner"
            loop Next line exists
                "s:Scanner" -> "s:Scanner" : nextLine()
                ":CompanyListDecoder" -> ":CompanyListDecoder" :parseInput(line)
            end

@enduml