@startuml
hide footbox
title Delete Dish Sequence Diagram

box "DeleteDishCommand"
participant ":DeleteDishCommand" as DeleteDishCommand
endbox

box "DishManager"
participant ":DishManager" as DishManager
endbox


-> DeleteDishCommand ++ : DeleteDishCommand(index)
-> DeleteDishCommand: execute(index)
DeleteDishCommand -> DishManager ++ : deleteDish(index)
DeleteDishCommand <-- DishManager
deactivate
<-- DeleteDishCommand: ui.printMessage()

destroy DeleteDishCommand
|||

@enduml