@startuml
'https://plantuml.com/sequence-diagram

hide footbox

-> ":AddCommand" : execute()

activate ":AddCommand"
    ":AddCommand" -> ":CompanyList" : add(companyName, industry, contactNumber, contactEmail)
    activate ":CompanyList"
    par
            ":CompanyList" -> ":CompanyList" : isDuplicateCompanyName(companyName)
            activate ":CompanyList"
                ":CompanyList" --> ":CompanyList"
            deactivate ":CompanyList"
            ":CompanyList" -> ":CompanyList" : isDuplicateContactEmail(contactEmail)
            activate ":CompanyList"
                ":CompanyList" --> ":CompanyList"
            deactivate ":CompanyList"
            ":CompanyList" -> ":CompanyList" : isDuplicateContactNumber(contactNumber)
            activate ":CompanyList"
                ":CompanyList" --> ":CompanyList"
            deactivate ":CompanyList"
    end
    ":CompanyList" --> ":AddCommand"
    deactivate ":CompanyList"

<-- ":AddCommand" :

destroy ":AddCommand"

@enduml
