@startuml

hide footbox
 -> "<<class>>\nCompanyListEncoder": write(companyList)
    activate "<<class>>\nCompanyListEncoder"
        "<<class>>\nCompanyListEncoder" -> "fw:FileWriter" ** : FileWriter(filePath)
        activate "fw:FileWriter"
            "fw:FileWriter" --> "<<class>>\nCompanyListEncoder" : fw
            deactivate "fw:FileWriter"

            "<<class>>\nCompanyListEncoder" -> "companyList:CompanyList": getNumberOfCompanies()
            activate "companyList:CompanyList"
            "companyList:CompanyList" --> "<<class>>\nCompanyListEncoder" : numberOfCompanies
            deactivate "companyList:CompanyList"
            opt numberOfCompanies == 0
                "<<class>>\nCompanyListEncoder" -> "fw:FileWriter" : write("")
                activate "fw:FileWriter"
                "fw:FileWriter" --> "<<class>>\nCompanyListEncoder"
                deactivate "fw:FileWriter"

                "<<class>>\nCompanyListEncoder" -> "fw:FileWriter" : close()
                activate "fw:FileWriter"
                "fw:FileWriter" --> "<<class>>\nCompanyListEncoder"
                deactivate "fw:FileWriter"

            end
            loop companies in companyList times
                "<<class>>\nCompanyListEncoder" -> "companyList:CompanyList": getCompany(index)
                activate "companyList:CompanyList"
                "<<class>>\nCompanyListEncoder" <-- "companyList:CompanyList": company
                deactivate "companyList:CompanyList"

                "<<class>>\nCompanyListEncoder" -> "<<class>>\nCompanyListEncoder": parseAndWriteToFile(company, fw)
                activate "<<class>>\nCompanyListEncoder"

                "<<class>>\nCompanyListEncoder" -> "company:Company": getCompanyName()
                activate "company:Company"
                "<<class>>\nCompanyListEncoder" <-- "company:Company": companyName
                deactivate "company:Company"

                "<<class>>\nCompanyListEncoder" -> "company:Company": getContactNumber()
                activate "company:Company"
                "<<class>>\nCompanyListEncoder" <-- "company:Company": contactNumber
                deactivate "company:Company"

                "<<class>>\nCompanyListEncoder" -> "company:Company": getContactEmail()
                activate "company:Company"
                "<<class>>\nCompanyListEncoder" <-- "company:Company": contactEmail
                deactivate "company:Company"

                "<<class>>\nCompanyListEncoder" -> "<<class>>\nCompanyListEncoder": convertConfirmStatusToBinary(confirmStatus)
                activate "<<class>>\nCompanyListEncoder"
                "<<class>>\nCompanyListEncoder" --> "<<class>>\nCompanyListEncoder": confirmStatus
                deactivate "<<class>>\nCompanyListEncoder"

                "<<class>>\nCompanyListEncoder" -> "company:Company": getIndustry()
                activate "company:Company"
                "<<class>>\nCompanyListEncoder" <-- "company:Company": industry
                deactivate "company:Company"

                "<<class>>\nCompanyListEncoder" -> "fw:FileWriter": write(companyName, contactNumber, contactEmail, confirmStatus, industry)
                activate "fw:FileWriter"
                "fw:FileWriter" --> "<<class>>\nCompanyListEncoder"
                deactivate "fw:FileWriter"
'
                "<<class>>\nCompanyListEncoder" --> "<<class>>\nCompanyListEncoder"
                deactivate "<<class>>\nCompanyListEncoder"
            end
            "<<class>>\nCompanyListEncoder" -> "fw:FileWriter": close()
            activate "fw:FileWriter"
            "<<class>>\nCompanyListEncoder" <-- "fw:FileWriter"
            deactivate "fw:FileWriter"
            <-- "<<class>>\nCompanyListEncoder"
            deactivate "<<class>>\nCompanyListEncoder"

@enduml
