@startuml
hide footbox
title Find Dish Sequence Diagram

box "FindDishCommand"
participant ":FindDishCommand" as FindDishCommand
endbox

box "DishManager"
participant ":DishManager" as DishManager
endbox

-> FindDishCommand ++ : FindDishCommand(stringToFind)
-> FindDishCommand: execute(stringToFind)
FindDishCommand -> DishManager ++ : findDish(stringToFind)
FindDishCommand <-- DishManager
deactivate
<-- FindDishCommand: ui.printMessage()

destroy FindDishCommand
|||
@enduml
