@startuml
hide footbox
":duke" -> ":Storage" : loadUserData()
activate ":Storage"


    ":Storage" -> ":UserCareerStorage": loadFromJson()
    activate ":UserCareerStorage"
        ":UserCareerStorage"-> ":UserCareerData": UserCareerData()
        activate ":UserCareerData"
            loop sessions in file times
                ":UserCareerStorage" -> ":UserCareerData" : addWorkoutSession()
            end
            ":UserCareerData" --> ":UserCareerStorage" : :UserCareerData
        ":UserCareerStorage" --> ":Storage" : :UserCareerData
    deactivate ":UserCareerData"
    deactivate ":UserCareerStorage"
    ":Storage" --> ":duke" : :UserCareerData
deactivate ":Storage"
":duke" -> ":Storage" : loadUserPlans()
    activate ":Storage"

    ":Storage" -> ":UserCareerStorage" : loadPlanFromJson()
    activate ":UserCareerStorage"
    ":UserCareerStorage" -> ":UserPlan" : UserPlan()
    activate ":UserPlan"
    loop days in a week times
            loop plans from file in a day times
                ":UserCareerStorage" -> ":UserPlan" : addDayPlan()
            end
    end
    ":UserPlan" --> ":UserCareerStorage" : :UserPlan
    deactivate ":UserPlan"
    ":UserCareerStorage" --> ":Storage" : :UserPlan
    deactivate ":UserCareerStorage"
    ":Storage" --> ":duke" : :UserPlan
    destroy ":UserCareerStorage"

deactivate ":Storage"


@enduml
