@startuml
hide footbox
":duke" -> ":StorageHandler" : loadUserData()
activate ":StorageHandler"
create ":UserDataLoader"

":StorageHandler" -> ":UserDataLoader" : <<create>>
activate ":UserDataLoader"
":UserDataLoader" --> ":StorageHandler"
deactivate ":UserDataLoader"

    ":StorageHandler" -> ":UserDataLoader": loadFromJson()
    activate ":UserDataLoader"
        ":UserDataLoader"-> ":UserCareerData": UserCareerData()
        activate ":UserCareerData"
            loop sessions in file times
                ":UserDataLoader" -> ":UserCareerData" : addWorkoutSession()
            end
            ":UserCareerData" --> ":UserDataLoader" : :UserCareerData
        ":UserDataLoader" --> ":StorageHandler" : :UserCareerData
    deactivate ":UserCareerData"
    deactivate ":UserDataLoader"
    ":StorageHandler" --> ":duke" : :UserCareerData
deactivate ":StorageHandler"
":duke" -> ":StorageHandler" : loadUserPlans()
    activate ":StorageHandler"

    ":StorageHandler" -> ":UserDataLoader" : loadPlansFromJson()
    activate ":UserDataLoader"
    ":UserDataLoader" -> ":UserPlan" : UserPlan()
    activate ":UserPlan"
    loop days in a week times
            loop plans from file in a day times
                ":UserDataLoader" -> ":UserPlan" : addDayPlan()
            end
    end
    ":UserPlan" --> ":UserDataLoader" : :UserPlan
    deactivate ":UserPlan"
    ":UserDataLoader" --> ":StorageHandler" : :UserPlan
    deactivate ":UserDataLoader"
    ":StorageHandler" --> ":duke" : :UserPlan
    destroy ":UserDataLoader"

deactivate ":StorageHandler"


@enduml
