@startuml
!include style.puml
hide footbox

participant ":Main" as main

main++ MAIN_COLOUR
'create ":Parser" as commandHandler LOGIC_COLOUR
main -> commandHandler ++ LOGIC_COLOUR : startWorkout()
participant ":Session" as session
commandHandler -> session ++ DATA_COLOUR : new Session()
session --> commandHandler --  : Session
commandHandler --> main -- : Session

main -> commandHandler ++ LOGIC_COLOUR : endWorkout()
commandHandler -> ":Storage" ++ STORAGE_COLOUR : writeToJson()
":Storage" --> commandHandler
deactivate ":Storage"
participant ":Ui" as ui
commandHandler -> ui ++ UI_COLOUR : printCompleteMessage()
ui --> commandHandler
deactivate ui
commandHandler --> main
deactivate commandHandler
@enduml