@startuml
hidefootbox
!include style.puml
CommandHandler -> PlannerCommandHandler: plannerCommandHandler()
activate PlannerCommandHandler SEA
PlannerCommandHandler-->CommandHandler: exit()
deactivate PlannerCommandHandler
@enduml