@startuml
hidefootbox
CommandHandler -> PlannerCommandHandler: plannerCommandHandler()
activate PlannerCommandHandler
PlannerCommandHandler-->CommandHandler: exit()
deactivate PlannerCommandHandler
@enduml