@startuml
hide footbox
box Storage
-> ":Storage" :  Storage()
create ":Storage"
activate ":Storage"
create ":GsonBuilder"
":Storage" -> ":GsonBuilder" : <<create>>
activate ":GsonBuilder"
create ":EventListAdapter"
":Storage" -> ":EventListAdapter" : <<create>>
activate ":EventListAdapter"
":EventListAdapter" --> ":GsonBuilder"
deactivate ":EventListAdapter"
":GsonBuilder" --> ":Storage"
deactivate ":GsonBuilder"
create ":Gson"
":Storage" -> ":Gson" : <<create>>
activate ":Gson"
deactivate ":GsonBuilder"
":Gson" --> ":Storage" : gson
deactivate ":Gson"
deactivate ":Storage"
end box
box java.io
participant ":File"
participant ":InputStreamReader"
participant ":FileWriter"
end box
":Storage" -> ":Storage" :loadEvents()
activate ":Storage"
create ":File"
":Storage" -> ":File" : load file from local save
activate ":File"
create ":ArrayList<Event>"
":Storage" -> ":ArrayList<Event>" : <<create>>
activate ":ArrayList<Event>"
alt !File.exists()
    ":ArrayList<Event>"--> ":Storage" : empty ArrayList<Event>
else File exists
    create ":InputStreamReader"
    ":File" -> ":InputStreamReader" : <<create>>
    activate ":InputStreamReader"
    ":InputStreamReader" -> ":Gson" : fromJson()
    deactivate ":InputStreamReader"
    activate ":Gson"
    ":Gson" --> ":ArrayList<Event>"
    deactivate ":Gson"
    ":ArrayList<Event>" --> ":Storage"
    deactivate ":ArrayList<Event>"
    deactivate ":File"
    deactivate ":Storage"
    end

":Storage"-> ":Storage" :saveToFile()

activate ":Storage"
":Storage" -> ":File" : <<create>> if file does not exist
activate ":File"
":Storage" -> ":ArrayList<Event>"
activate ":ArrayList<Event>"
":Storage" -> ":Gson"
activate ":Gson"
":ArrayList<Event>" --> ":Gson"
deactivate ":ArrayList<Event>"

create "gsonData : String"
":Gson" -> "gsonData : String" : toJson()
deactivate ":Gson"
activate "gsonData : String"

create ":FileWriter"
":Storage" -> ":FileWriter" : <<create>>
activate ":FileWriter"
"gsonData : String" --> ":FileWriter"
deactivate "gsonData : String"
":FileWriter" --> ":File"
deactivate ":FileWriter"
":File" --> ":Storage"
deactivate ":File"
deactivate ":Storage"
@enduml