@startuml
skinparam classAttributeIconSize 0
hide circle
class StorageHandler{
- userDataLoader: UserDataLoader
- userDataLoader: UserDataWriter
- FilePath: String
+ StorageHandler(String: FilePath)
+ writeToJson(UserCareerData) : void
+ loadUserCareer() : UserCareerData
}

class UserDataLoader{
- gson : Gson
+ UserDataLoader(Gson gson)
+ loadFromJson(String FilePath): UserCareerData
}

class UserDataWriter{
- gson : Gson
+ UserDataWriter(Gson gson)
+ saveToJson(Sting filePath,UserCareerData UserCareerData): void
}

class UserCareerData{
}

class Session{
}


StorageHandler --> "1" UserDataWriter
StorageHandler --> "1" UserDataLoader
UserDataLoader --> "1" UserCareerData
UserCareerData --> "*" Session


@enduml