@startuml
skinparam classAttributeIconSize 0
hide circle
left to right direction

class LocalDateAdapter {
+ deserialize(JsonElement,Type,JsonDeserializationContext):LocalDateTime
+ serialize(LocalDateTime,Type,JsonSerializationContext):JsonElement
}
class StorageHandler {
- userDataWriter : UserDataWriter
- userDataLoader : UserDataLoader
- filePath : String
+ void writeToJson(UserCareerData)
+ void writeToJson(UserPlan)
+ UserCareerData loadUserCareer()
+ UserPlan loadUserPlans()
}
class UserDataLoader {
- Gson gson
+ loadFromJson(String) : UserCareerData
+ loadPlanFromJson(String) : UserPlan
}
class UserDataWriter {
- Gson gson
+ saveToJson(String,UserCareerData) : boolean
+ saveToJson(String,UserPlan) : boolean
}

class UserPlan {
- plan : ArrayList<Plan>[]
+ addDayPlan(Plan) : void
}

class Session{
- sessionExercises : ArrayList<ExerciseData>
}
interface Storage <<interface>>{
}

class UserCareerData{
- Sessions : ArrayList<Session>
}

UserDataLoader . UserCareerData : writes to >
UserDataLoader .. "1" UserPlan : writes to >
UserCareerData . UserDataWriter : gets data from <
UserPlan .. UserDataWriter : gets data from <
UserCareerData *-- "*" Session

Storage <|.. StorageHandler

StorageHandler -> "1" UserDataLoader
StorageHandler -> "1" UserDataWriter

google.gson.JsonSerializer <|... LocalDateAdapter
google.gson.JsonDeserializer <|... LocalDateAdapter
@enduml
