@startuml
skinparam classAttributeIconSize 0
hide circle
!include style.puml
class StorageManager MAIN_COLOUR {
}
interface Storage <<interface>> STORAGE_COLOUR {
+writeToJson(UserCareerData) : void
+loadUserData() : UserCareerData


+writeToJson(UserPlan) : void
+loadUserPlans() : UserPlan
}
class JsonUserPlansStorage LAPIS {

}
interface UserPlansStorage <<interface>> ORANGE {

}

class JsonUserCareerStorage LAPIS {
}
abstract class TextDataUtility {
}
class JsonUserPlansWriter DATA_COLOUR {
}
interface UserCareerStorage <<interface>> ORANGE {
}
class JsonUserDataWriter DATA_COLOUR {
}
class JsonUserPlansLoader DATA_COLOUR {
}
class JsonUserDataLoader DATA_COLOUR {
}

StorageManager .d.|> Storage
StorageManager --> UserCareerStorage
StorageManager --> UserPlansStorage
UserCareerStorage <|-l- Storage
UserPlansStorage <|-r- Storage
UserPlansStorage <|.. JsonUserPlansStorage

UserCareerStorage <|.. JsonUserCareerStorage

JsonUserCareerStorage -d--> JsonUserDataLoader
JsonUserCareerStorage -d--> JsonUserDataWriter
JsonUserPlansStorage -d--> JsonUserPlansLoader
JsonUserPlansStorage -d--> JsonUserPlansWriter

@enduml