@startuml
skinparam classAttributeIconSize 0
hide circle
!include style.puml
class storage.StorageManager MAIN_COLOUR {
}
interface storage.Storage <<interface>> STORAGE_COLOUR {
writeToJson(UserCareerData) : void
loadUserData() : UserCareerData


writeToJson(UserPlan) : void
loadUserPlans() : UserPlan
}
class storage.JsonUserPlansStorage LAPIS {

}
interface storage.UserPlansStorage <<interface>> ORANGE {

}

class storage.JsonUserCareerStorage LAPIS {
}
abstract class storage.TextDataUtility {
}
class storage.JsonUserPlansWriter DATA_COLOUR {
}
interface storage.UserCareerStorage <<interface>> ORANGE {
}
class storage.JsonUserDataWriter DATA_COLOUR {
}
class storage.JsonUserPlansLoader DATA_COLOUR {
}
class storage.JsonUserDataLoader DATA_COLOUR {
}

storage.StorageManager .d.|> storage.Storage
storage.StorageManager --> storage.UserCareerStorage
storage.StorageManager --> storage.UserPlansStorage
storage.UserCareerStorage <|-l- storage.Storage
storage.UserPlansStorage <|-r- storage.Storage
storage.UserPlansStorage <|.. storage.JsonUserPlansStorage

storage.UserCareerStorage <|.. storage.JsonUserCareerStorage

storage.JsonUserCareerStorage -d--> storage.JsonUserDataLoader
storage.JsonUserCareerStorage -d--> storage.JsonUserDataWriter
storage.JsonUserPlansStorage -d--> storage.JsonUserPlansLoader
storage.JsonUserPlansStorage -d--> storage.JsonUserPlansWriter

@enduml