@startuml
!define DINERDIRECTOR_COLOR #yellow
!define PARSER_COLOR #orange
!define COMMAND_COLOR #magenta
!define UI_COLOR #lightgreen
!define MANAGER_COLOR #violet
!define ENTITY_COLOR #darkgreen
!define STORAGE_COLOR #pink

skinparam classAttributeIconSize 0
hide circle
hide footbox

@enduml
