@startuml
skinparam classAttributeIconSize 0
hide circle
!include style.puml

Class Bye MAROON {
+ bye()
}

Class Greet SEA {
+ greet()
}

Class PrintExercises ORANGE {
+ printExercises(ArrayList<ExerciseData>)
}

Class PrintPlanner DATA_COLOUR {
+ printPlanner(UserPlan)
+ printPlannerGreeting()
}

Class PrintHelpMessage LAPIS {
+ showAvailableCommands()
+ showAvailablePlannerCommands()
+ printFiltersAvailable()
+ unknownCommandMessage()
}

Class PrintUserExerciseData DATA_COLOUR {
+ printUserExerciseHistory(HashMap<String,Integer>)
}

Class Ui MAIN_COLOUR {
+ printExerciseFromList (ArrayList<ExerciseData>)
+ greetUser()
+ byeUser()
+ printFilters()
+ unknownCommand()
+ showPlan(UserPlan)
+ printHelp()
+ printPlannerHelp()
+ splitLine()
+ printUserExerciseHistory(HashMap<String, Integer>)
+ printPlannerGreeting()
}

left to right direction
Bye <.. Ui
Greet <.. Ui
PrintExercises <.. Ui
PrintPlanner <.. Ui
PrintHelpMessage <.. Ui
PrintUserExerciseData <.. Ui

@enduml