@startuml
'https://plantuml.com/sequence-diagram

hide footbox



activate ":Eventus"
":Eventus" -> ":Eventus" : run()
activate ":Eventus"

":Eventus" -> ":Ui" : showWelcome()

activate ":Ui"

    ":Ui" -> ":Ui": showLine()
    activate ":Ui"

    ":Ui" --> ":Ui":
    deactivate ":Ui"

    ":Eventus" <-- ":Ui"

deactivate ":Ui"

":Eventus" --> ":Eventus"

deactivate ":Eventus"


@enduml