@startuml
'https://plantuml.com/class-diagram

hide circle
skinparam classAttributeIconSize 0


class Ui {
+showLine()
+showWelcome()
+showGuide()
+showExitMessage()
+showHelpText()
+showSuccessfulDeletionMessage()
+showSuccessfulAdditionMessage()
+showSuccessfulPurgingMessage()
+showSampleDataLoadedMessage()
+showSuccessfulConfirmedMessage()
+showSuccessfulUnconfirmedMessage()
+showExistingConfirmationMessage()
+showExistingUnconfirmationMessage()
+showSortedCompanyList()
+showCompanyFoundMessage()
+showCompanyNotFoundMessage()
+showVenueSelectionMessage()
+showEventNameSelectionMessage()
+emptyInputErrorMessage()
+invalidInputFormatErrorMessage()
+invalidInputFormatErrorMessage()
+multipleAdditionErrorMessage()
}


@enduml
