@startuml
'https://plantuml.com/class-diagram
!include Style.puml
title UI Class Diagram

class DinerDirector DINERDIRECTOR_COLOR {
}


class TextUi UI_COLOR{
    - in:Scanner
    - out:PrintStream
    + TextUi()
    + TextUi(in:InputStream, out:PrintStream)
    - shouldIgnoreEmpty(fullUserInput:String) : boolean
    + getUserInput() : String
    + printMessage(message: String) : void
    + {static} printBanner() : void
}

class XYZManager MANAGER_COLOR {
}

DinerDirector --> TextUi: read user input with >
XYZManager --> TextUi: print command output with >

@enduml