@startuml
'https://plantuml.com/sequence-diagram

activate DinerDirector

DinerDirector -> Parser: parseCommand(userInput)
activate Parser

Parser -> Parser: prepareViewDeadlineCommand(userInputNoCommand)
activate Parser
Parser --> Parser : Command
deactivate Parser

Parser --> DinerDirector : Command
deactivate Parser
destroy Parser

DinerDirector -> ViewDeadlineCommand: execute(ui)
activate ViewDeadlineCommand

ViewDeadlineCommand -> DeadlineManager: printDeadlines(ui)
activate DeadlineManager

DeadlineManager -> TextUi: printMessage(list)
activate TextUi

TextUi -> DeadlineManager
deactivate TextUi
destroy TextUi

DeadlineManager -> ViewDeadlineCommand
deactivate DeadlineManager
destroy DeadlineManager

ViewDeadlineCommand -> DinerDirector
deactivate ViewDeadlineCommand
destroy ViewDeadlineCommand


@enduml