@startuml
!include Style.puml
hide footbox
title View Dish Sequence Diagram

box "ViewDishCommand"
participant ":ViewDishCommand" as ViewDishCommand COMMAND_COLOR
endbox

box "DishManager"
participant ":DishManager" as DishManager MANAGER_COLOR
endbox

-> ViewDishCommand: execute()
activate ViewDishCommand
ViewDishCommand -> DishManager ++ : viewDish()
ViewDishCommand <-- DishManager
deactivate
<-- ViewDishCommand:

|||
destroy ViewDishCommand
@enduml