@startuml
hide footbox
title View Dish Sequence Diagram

box "ViewDishCommand"
participant ":ViewDishCommand" as ViewDishCommand
endbox

box "DishManager"
participant ":DishManager" as DishManager
endbox

-> ViewDishCommand: execute()
activate ViewDishCommand
ViewDishCommand -> DishManager ++ : viewDish()
ViewDishCommand <-- DishManager
deactivate
<-- ViewDishCommand:

|||
destroy ViewDishCommand
@enduml