@startuml
'https://plantuml.com/sequence-diagram

activate DinerDirector

DinerDirector -> Parser: parseCommand(String userInput)
activate Parser

Parser -> Parser: prepareViewDeadlineCommand(String userInputNoCommand)
activate Parser
Parser --> Parser
deactivate Parser

Parser --> DinerDirector
deactivate Parser

DinerDirector -> ViewDeadlineCommand: execute(TextUi ui)
activate ViewDeadlineCommand

ViewDeadlineCommand -> DeadlineManager: printDeadlines(TextUi ui)

DeadlineManager -> TextUi: printMessage(String list)

@enduml