@startuml
hide footbox
!include style.puml

participant "Storage" as Storage
participant "JsonUserCareerStorage" as JsonUserCareerStorage
participant "JsonUserDataWriter" as JsonUserDataWriter
-> Storage : writeToJson(userCareerData)
activate Storage STORAGE_COLOUR

        Storage -> JsonUserCareerStorage : writeToJson(userCareerData)
            activate JsonUserCareerStorage LAPIS
                JsonUserCareerStorage -> JsonUserDataWriter : saveToJson(filepath,userCareerData)
            activate JsonUserDataWriter BLUE
            JsonUserDataWriter --> JsonUserCareerStorage : save status boolean
            deactivate JsonUserDataWriter
            JsonUserCareerStorage --> Storage
            deactivate JsonUserCareerStorage
<-- Storage



@enduml
