title: MoneyGoWhere

header_pages:
  - UserGuide.md
  - DeveloperGuide.md
  - AboutUs.md

markdown: kramdown

repository: "AY2223S1-CS2113T-T09-2/tp"

plugins:
  - jemoji
  - jekyll-remote-theme # add this line to the plugins list if you already have one

remote_theme: pages-themes/cayman@v0.2.0
