remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jemoji

title: "MovieMate"

markdown: kramdown
kramdown:
  parse_block_html: true


header_pages:
- UserGuide.md
- DeveloperGuide.md
- AboutUs.md

repository: "AY2223S2-CS2113-W12-4/tp"
