@startuml
title Notes Sequence Diagram
'https://plantuml.com/sequence-diagram

actor User

User -> Notes : setToDo()
activate Notes

Notes -> Ui : printNotes()
activate Ui
deactivate Ui
destroy Ui
ArrayList --> Notes : cache
deactivate Notes

@enduml