@startuml
'https://plantuml.com/sequence-diagram

activate Command
Command -> Quadratic: quadratic.solveQuadratic()
activate Quadratic
Quadratic -> QuadraticParser
activate QuadraticParser
QuadraticParser -> QuadraticParser : findA()
activate QuadraticParser #FFBBBB
deactivate QuadraticParser
QuadraticParser -> QuadraticParser : findB()
activate QuadraticParser #FFBBBB
deactivate QuadraticParser
QuadraticParser -> QuadraticParser : findC()
activate QuadraticParser #FFBBBB
deactivate QuadraticParser
QuadraticParser --> Quadratic
deactivate QuadraticParser
Quadratic -> Quadratic: quadraticFormula()
activate Quadratic #FFBBBB
deactivate Quadratic
Quadratic -> Quadratic: minMaxPointFinder()
activate Quadratic #FFBBBB
deactivate Quadratic
Quadratic -> Quadratic: printAnswer()
activate Quadratic #FFBBBB
Quadratic -> UI: Ui.printQuadraticAnswer()
activate UI
UI --> Quadratic
deactivate UI
deactivate Quadratic
opt Exceptions
Quadratic -> UI: printQuadraticFormatError()
activate UI
UI --> Quadratic
deactivate UI
end opt
Quadratic --> Command
deactivate Quadratic
@enduml