@startuml
'https://plantuml.com/sequence-diagram

activate Command
Command -> Quadratic: quadratic.solveQuadratic()
activate UI
activate Quadratic
Quadratic -> Quadratic: findA()
activate Quadratic #FFBBBB
deactivate Quadratic
Quadratic -> Quadratic: findB()
activate Quadratic #FFBBBB
deactivate Quadratic
Quadratic -> Quadratic: findC()
activate Quadratic #FFBBBB
deactivate Quadratic
Quadratic -> Quadratic: quadraticFormula()
activate Quadratic #FFBBBB
deactivate Quadratic
Quadratic -> Quadratic: printAnswer()
activate Quadratic #FFBBBB
Quadratic -> UI: Ui.printQuadraticAnswer()
activate UI
UI --> Quadratic
deactivate UI
deactivate Quadratic
opt Exceptions
Quadratic -> UI: printQuadraticFormatError()
activate UI
UI --> Quadratic
deactivate UI
end opt
deactivate Quadratic
Quadratic --> Command
@enduml