
abstract class Command{
    + abstract void execute()
    + void setData()
}
class SearchController{}
class SearchCommand{
    - String command
    - String action
    + void execute()
}
class BorrowableItem{}
class Inventory{}
class Book{}

SearchController -> Inventory
SearchController --> Book
Command <|- SearchCommand
SearchCommand --> SearchController
SearchCommand -> BorrowableItem
SearchCommand --> Book
