
@startuml
title MagusStock Overall Sequence Diagram

actor User
participant ":MagusStock"
participant "<<class>>\nUi"
participant "<<class>>\nSessionManager"
participant ":ParserHandler"
participant ":Inventory"
User -> ":MagusStock": run()
activate ":MagusStock"
":MagusStock" -> "<<class>>\nUi": greetUser()
activate "<<class>>\nUi"
"<<class>>\nUi" --> ":MagusStock":
deactivate "<<class>>\nUi"
":MagusStock" -> "<<class>>\nSessionManager": getSession()
activate "<<class>>\nSessionManager"
"<<class>>\nSessionManager" --> ":MagusStock":
deactivate "<<class>>\nSessionManager"
":MagusStock" -> "<<class>>\nSessionManager": getSessionAlerts()
activate "<<class>>\nSessionManager"
"<<class>>\nSessionManager" --> ":MagusStock":
deactivate "<<class>>\nSessionManager"
":MagusStock" -> ":Inventory": setAlertList()
activate ":Inventory"
":Inventory" --> ":MagusStock":
deactivate ":Inventory"
":MagusStock" -> ":ParserHandler"**:
activate ":ParserHandler"
":ParserHandler" --> ":MagusStock":
deactivate ":ParserHandler"
":MagusStock" -> ":MagusStock": run()
activate ":MagusStock"
loop user send input "bye" or "exit"
":MagusStock" -> ":ParserHandler": run()
activate ":ParserHandler"
":ParserHandler" -> ":Inventory":
activate ":Inventory"
ref over ":ParserHandler", ":Inventory": Parse user input and execute command
":Inventory" --> ":ParserHandler":
destroy ":Inventory"
deactivate ":Inventory"
":ParserHandler" --> ":MagusStock":
deactivate ":ParserHandler"
destroy ":ParserHandler"
":MagusStock" --> ":MagusStock":
deactivate ":MagusStock"
end
destroy ":MagusStock"


@enduml