@startuml
'https://plantuml.com/sequence-diagram

title ListModuleCommand

participant Parser as Parser

participant ListModuleCommand as ListMod

Parser -> ListMod : ListModuleCommand()
activate ListMod
ListMod -> LoggerInterface : setUpLogger()

activate LoggerInterface
deactivate LoggerInterface
destroy LoggerInterface

ListMod -> Module: Module()
activate Module
Module -> ListMod
deactivate Module
deactivate ListMod

Parser -> ListMod : execute()
activate ListMod

alt args.length == 3
    ListMod -> ListMod : handleMultiCommand()
else
    ListMod -> ModuleList : add()
    activate ModuleList
    ModuleList -> ListMod
    deactivate ModuleList

    ListMod -> ModuleList : sortModuleList()
    activate ModuleList
    ModuleList -> ListMod
    deactivate ModuleList
    destroy ModuleList

    ListMod -> Module: findModules()
    activate Module
    Module -> ListMod
    deactivate Module
    destroy Module

    ListMod -> Ui : printAddModuleMessage()
    activate Ui
    Ui -> ListMod
    deactivate Ui
    destroy Ui
end

ListMod -> Storage : saveModuleList()
activate Storage
Storage -> ListMod
deactivate Storage
destroy Storage

destroy ListMod
@enduml